version: '3.7'

services:
  web:
    image: 754963640892.dkr.ecr.us-east-1.amazonaws.com/commute_web
    build:
      context: ./webapp
      dockerfile: Dockerfile
      target: Django
    volumes:
      - static_volume:/webapp/backend/static
      # - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: 754963640892.dkr.ecr.us-east-1.amazonaws.com/commute_db
    build:
      context: ./webapp
      dockerfile: Dockerfile
      target: DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx-proxy:
    image: 754963640892.dkr.ecr.us-east-1.amazonaws.com/commute_nginx-proxy
    container_name: nginx-proxy
    build: ./webapp/nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/webapp/backend/static
      # - media_volume:/home/app/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme: