version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - type: bind
    #     source: ./postgis-data
    #     target: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432