version: '3.7'

services:
  web:
    image: postgis/postgis:13-3.1-alpine
    # volumes:
    #   - type: bind
    #     source: ./postgis-data
    #     target: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432